# Generated by Django 5.2 on 2025-05-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
